<a href="https://colab.research.google.com/github/mohamadwael453/AI-Data-scientest-Diplom/blob/main/learn/Libraries%20%26%20Mathematics/Lec15(MATRICES_%26_NumPy_Foundations_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learn

## 📌 Matrices – Complete Overview

A matrix is a rectangular arrangement of numbers organized into rows and columns, and it is one of the most important mathematical tools used in engineering and science. It allows us to represent data, solve systems of equations, and model complex systems such as electrical networks and control systems.

A matrix is typically written in the form:

A = [ a11  a12  a13
      a21  a22  a23 ]

where the horizontal elements are called rows and the vertical elements are called columns. The size of a matrix is defined as m × n, where m is the number of rows and n is the number of columns. For example:

A = [ 1  2
      3  4 ]

This is a 2 × 2 matrix.

There are several common types of matrices. A row matrix has only one row, while a column matrix has only one column. A square matrix has the same number of rows and columns. A zero matrix contains only zeros, and an identity matrix has ones on the main diagonal and zeros elsewhere, such as:

I = [ 1  0
      0  1 ]

Matrices support several important operations. Two matrices can be added only if they have the same size, and the addition is done element by element. A matrix can also be multiplied by a scalar, which means multiplying every element by a constant. Matrix multiplication is more complex and requires that the number of columns of the first matrix equals the number of rows of the second matrix. The result is a new matrix whose size depends on the outer dimensions. Another important operation is the transpose, where rows and columns are swapped.

In programming, matrices are commonly implemented using the **:contentReference[oaicite:0]{index=0}** library in Python. For example:

```python
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

A + A      # Addition
A * 2      # Scalar multiplication
A @ A      # Matrix multiplication
A.T        # Transpose

## 📌 Types of Matrices

Matrices can be classified based on their shape, size, and element properties.  
Understanding these types is essential for solving engineering problems efficiently.

---

## 🔹 1. Row Matrix
A row matrix contains only **one row**.

A = [ a₁  a₂  a₃  ...  aₙ ]  
Size → 1 × n  

👉 Used to represent horizontal data or transposed vectors.

---

## 🔹 2. Column Matrix
A column matrix contains only **one column**.

A = [ a₁  
      a₂  
      a₃  
      ...  
      aₙ ]  
Size → n × 1  

👉 Commonly used to represent vectors in engineering systems.

---

## 🔹 3. Rectangular Matrix
A matrix where:

m ≠ n (rows ≠ columns)

👉 Used in real-world datasets and input-output systems.

---

## 🔹 4. Square Matrix
A matrix where:

m = n (same number of rows and columns)

👉 Important because:
- Determinant exists  
- Inverse exists  
- Used in system modeling  

---

## 🔹 5. Zero (Null) Matrix
All elements are zero.

O = [ 0  0  
      0  0 ]

👉 Acts as **additive identity** (A + O = A)

---

## 🔹 6. Identity Matrix
Diagonal elements = 1, others = 0.

I = [ 1  0  
      0  1 ]

👉 Acts as **multiplicative identity** (A × I = A)

---

## 🔹 7. Diagonal Matrix
All elements outside the diagonal are zero.

👉 Only diagonal values may be non-zero  
👉 Simplifies many calculations  

---

## 🔹 8. Scalar Matrix
A special diagonal matrix where:

All diagonal elements are equal

A = [ k  0  
      0  k ]

👉 Acts like scalar multiplication

---

## 🔹 9. Upper Triangular Matrix
All elements **below** the main diagonal are zero.

👉 Used in solving equations (LU decomposition)

---

## 🔹 10. Lower Triangular Matrix
All elements **above** the main diagonal are zero.

👉 Also used in numerical methods

---

## 🔹 11. Symmetric Matrix
A matrix where:

A = Aᵀ

👉 Elements are mirrored across the diagonal  
👉 Common in physics and engineering models  

---

## 🔹 12. Skew-Symmetric Matrix
A matrix where:

Aᵀ = -A  

👉 Diagonal elements = 0  
👉 Used in rotational systems  



## 📌 Matrix Operations – Clear & Structured Overview

Matrix operations are mathematical rules used to manipulate matrices.  
They are essential in solving equations, modeling systems, and performing computations in engineering and science.

---

## 🔹 1. Matrix Addition
Two matrices can be added only if they have the **same size**.

A + B = [ a11+b11     a12+b12  
          a21+b21   a22+b22 ]

👉 Add corresponding elements  
👉 Same dimensions required  

---

## 🔹 2. Matrix Subtraction
Similar to addition, but subtract elements.

A - B = [ a11-b11   a12-b12  
          a21-b21   a22-b22 ]

👉 Same size condition applies  

---

## 🔹 3. Scalar Multiplication
Multiply each element of a matrix by a constant k.

kA = [ k·a11   k·a12  
       k·a21   k·a22 ]

👉 Changes magnitude of all elements  

---

## 🔹 4. Matrix Multiplication
Two matrices can be multiplied if:

(columns of A) = (rows of B)

👉 Result size:
(m × n) × (n × p) = (m × p)

Example:
A (2×3) × B (3×2) → Result (2×2)

👉 Multiply rows by columns  

---

## 🔹 5. Transpose
Swap rows and columns of a matrix.

Aᵀ

👉 Row becomes column  
👉 Column becomes row  

---

## 🔹 6. Determinant (Basic Idea)
Only for square matrices.

For 2×2:
|A| = (a11·a22) − (a12·a21)

👉 Used to check:
- If matrix is invertible  
- System solvability  

---

## 🔹 7. Inverse of a Matrix
Only exists if determinant ≠ 0.

A⁻¹

👉 Property:
A · A⁻¹ = I

👉 Used to solve equations:
AX = B → X = A⁻¹B  

---

## 🔹 8. Element-wise Multiplication
Multiply elements directly (not matrix multiplication).

A ⊙ B

👉 Same size required  
👉 Different from normal multiplication  

---

## 🧠 Matrix Operations in Python

Using **:contentReference[oaicite:0]{index=0}**:

```python
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A + B        # Addition
A - B        # Subtraction
A * 2        # Scalar multiplication
A @ B        # Matrix multiplication
A.T          # Transpose
np.linalg.det(A)    # Determinant
np.linalg.inv(A)    # Inverse
A * B        # Element-wise multiplication

## 📌 Linear Equations – Clear & Structured Overview

A linear equation is an equation in which the highest power of the variable is 1.  
It represents a straight-line relationship between variables and is one of the most fundamental concepts in mathematics and engineering.

---

## 🔹 1. General Form
A linear equation in one variable is written as:

ax + b = 0  

👉 a, b → constants  
👉 x → unknown variable  

---

## 🔹 2. Solution of Linear Equation
To solve:

ax + b = 0  

👉 Move constant:
ax = -b  

👉 Divide:
x = -b / a  

---

## 🔹 3. Linear Equation in Two Variables
General form:

ax + by = c  

👉 Represents a straight line  
👉 Has infinite solutions  

Example:
2x + y = 5  

---

## 🔹 4. Graph Representation
A linear equation forms a **straight line** on a graph.


::contentReference[oaicite:0]{index=0}


👉 m → slope (rate of change)  
👉 c → y-intercept  

---

## 🔹 5. Slope (m)
Slope measures how steep the line is:

m = (change in y) / (change in x)

👉 m > 0 → increasing line  
👉 m < 0 → decreasing line  
👉 m = 0 → horizontal line  

---

## 🔹 6. Special Cases
- Horizontal line → y = constant  
- Vertical line → x = constant  
- Parallel lines → same slope  
- Perpendicular lines → slopes multiply to -1  

---

## 🔹 7. System of Linear Equations
Multiple linear equations solved together.

Example:
x + y = 5  
x - y = 1  

👉 Solution:
x = 3, y = 2  

---

## 🔹 8. Methods of Solving
- Substitution method  
- Elimination method  
- Matrix method (important in engineering)  

---

## 🧠 Linear Equations in Python

Using **:contentReference[oaicite:1]{index=1}**:

```python
import numpy as np

A = np.array([[1, 1],
              [1, -1]])

B = np.array([5, 1])

X = np.linalg.solve(A, B)
print(X)

In [ ]:
import numpy as np
rng = np.random.default_rng(seed = 12585)
x1 = rng.integers(50 ,size =8 )
x2 = rng.integers(500 ,size = (4,3))
x3 = rng.integers (9 , size =  (4,2,2))
print(x1)
print(x2)
print(x3)

[37 17  9  5 40  6 48 39]
[[151 268  80]
 [283 468 230]
 [244 366 285]
 [233 106 282]]
[[[5 2]
  [6 6]]

 [[7 2]
  [7 5]]

 [[2 4]
  [1 0]]

 [[7 5]
  [8 8]]]


In [ ]:
print("-" * 40)
print("Array Attributes for x2 (3x4 matrix):")
print("-" * 40)
print(f"ndim:  {x2.ndim}      ← Number of dimensions (axes)")
print(f"shape: {x2.shape}  ← Size along each dimension (rows, cols)")
print(f"size:  {x2.size}     ← Total number of elements (3x4=12)")
print(f"dtype: {x2.dtype}   ← Data type of elements")


----------------------------------------
Array Attributes for x2 (3x4 matrix):
----------------------------------------
ndim:  2      ← Number of dimensions (axes)
shape: (4, 3)  ← Size along each dimension (rows, cols)
size:  12     ← Total number of elements (3x4=12)
dtype: int64   ← Data type of elements


## 📌 Understanding Array Structure

Understanding array structure is one of the most important fundamentals in **:contentReference[oaicite:0]{index=0}**.  
Before performing mathematical operations, reshaping data, or building machine learning models, it is essential to understand how arrays are organized in memory and how their dimensions affect computations.

---

### 🔹 What is an Array Structure?

An array structure describes:
- The shape of the array  
- The number of dimensions  
- The data type of elements  
- The amount of memory used  

These properties determine how efficiently data can be processed and manipulated.


## 📌 Accessing Data — Indexing in NumPy

Indexing is the process of accessing, selecting, and modifying elements inside an array. Almost every operation in data science, engineering, ML, and image processing depends on it.

**Indexing allows us to:**
- Access specific values in datasets
- Extract rows and columns from matrices
- Get predictions from ML models
- Extract pixels from images
- Filter and manipulate data efficiently

---

### 🔹 1D Array Indexing

A 1D array behaves similarly to a Python list.

```python
import numpy as np
A = np.array([10, 20, 30, 40, 50])
```

**Access individual elements:**

```python
A[0]      # First element → 10
A[2]      # Third element → 30
A[-1]     # Last element  → 50
```

> 👉 Negative indexing starts from the end of the array.

**Slicing syntax:** `array[start : stop : step]`

```python
A[1:4]    # Elements index 1 to 3  → [20, 30, 40]
A[:3]     # First 3 elements       → [10, 20, 30]
A[2:]     # From index 2 to end    → [30, 40, 50]
A[::2]    # Every second element   → [10, 30, 50]
A[::-1]   # Reverse array          → [50, 40, 30, 20, 10]
```

---

### 🔹 2D Array Indexing

A 2D array is indexed using `[row, column]`.

```python
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
```

**Access individual elements:**

```python
A[0, 0]    # Row 0, col 0 → 1
A[1, 2]    # Row 1, col 2 → 6
A[2, 1]    # Row 2, col 1 → 8
```

**Access rows and columns:**

```python
A[0, :]    # First row       → [1, 2, 3]
A[:, 1]    # Second column   → [2, 5, 8]
A[:, :]    # Entire matrix
```

> 👉 `:` means select all elements in that dimension.

**2D slicing:**

```python
A[0:2, 1:3]
# Rows 0–1, Cols 1–2
# → [[2, 3],
#    [5, 6]]
```

---

### 🔹 Modifying Array Values

Arrays are mutable — values can be changed directly.

```python
# 1D
A = np.array([10, 20, 30])
A[0] = 100
# → [100, 20, 30]

# 2D
A = np.array([[1, 2],
              [3, 4]])
A[1, 1] = 50
# → [[ 1,  2],
#    [ 3, 50]]
```

---

### 🔹 Boolean Indexing

Boolean indexing filters elements based on a condition.

```python
A = np.array([1, 2, 3, 4, 5])
A[A > 2]
# → [3, 4, 5]
```

> 👉 Very useful in data analysis, machine learning, and signal filtering.

---

### 🔹 Fancy Indexing

Fancy indexing accesses multiple elements using a list of indices.

```python
A = np.array([10, 20, 30, 40, 50])
A[[0, 2, 4]]
# → [10, 30, 50]
```

---

### 🔹 Important Array Attributes

```python
A.shape    # Shape of the array, e.g. (3, 3)
A.ndim     # Number of dimensions
A.size     # Total number of elements
A.dtype    # Data type (int64, float32, etc.)
```

---

### 🔹 Common Indexing Patterns — Quick Reference

```python
A[0]       # First element
A[-1]      # Last element
A[:5]      # First five elements
A[1:]      # From index 1 to end
A[::2]     # Every second element
A[::-1]    # Reverse order
```

---

### 💡 Why Indexing Matters

Indexing is heavily used in:
- Image processing (pixel extraction)
- Signal processing
- Matrix computations
- Machine learning datasets
- Power systems simulations

Efficient indexing improves performance, memory usage, and code readability.

---

### 📚 Summary

| Type | Syntax | Use |
|---|---|---|
| 1D indexing | `A[i]` | Single element access |
| 1D slicing | `A[start:stop:step]` | Range extraction |
| 2D indexing | `A[row, col]` | Matrix element access |
| 2D slicing | `A[r1:r2, c1:c2]` | Sub-matrix extraction |
| Boolean | `A[A > val]` | Condition-based filtering |
| Fancy | `A[[i, j, k]]` | Multi-index selection |
| Mutation | `A[i] = val` | In-place modification |

In [ ]:
print(f"x1 = {x1}")
print(f"     {''.join([str(i).center(3) for i in range(len(x1))])} ← positive index")
print(f"     {''.join([str(i-len(x1)).center(3) for i in range(len(x1))])} ← negative index")

In [ ]:
print(f"x1[0]  = {x1[0]}   ← First element")
print(f"x1[-1] = {x1[-1]}   ← Last element")
print(f"x1[-2] = {x1[-2]}   ← Second to last")

In [ ]:
print("x2 (3x4 matrix):")
print(x2)
print()
print(f"x2[0, 0] = {x2[0, 0]}  ← Top-left corner (row 0, col 0)")
print(f"x2[1, 0] = {x2[1, 0]}  ← Row 1, col 0")
print(f"x2[2, -1] = {x2[2, -1]}  ← Row 2, last column")

In [ ]:
# 3D indexing: [page, row, column]
print(f"x3 shape: {x3.shape}")
print(f"x3[1, 2, 3] = {x3[1, 2, 3]}  ← Page 1, Row 2, Col 3")

In [ ]:
print("Before modification:")
print(x2)

x2[0, 0] = 999  # Modify single element

print("\nAfter x2[0, 0] = 999:")
print(x2)

### View vs. Copy Cheat Sheet

| Operation | Returns | Example |
|-----------|---------|--------|
| Basic slicing | **VIEW** | `arr[0:5]` |
| Reshape | **VIEW** | `arr.reshape(2, 3)` |
| Transpose | **VIEW** | `arr.T` |
| `.copy()` | **COPY** | `arr[0:5].copy()` |
| Fancy indexing | **COPY** | `arr[[0, 2, 4]]` |

**Rule of thumb**: If you're going to modify a subset and don't want to affect the original, always use `.copy()`!

#######################################################################


# 🔄 Reshaping & Restructuring Arrays — NumPy

> Understanding how to reshape and restructure arrays is essential before building ML pipelines, processing signals, or feeding data into any computation engine.

---

## 🗂️ Index

| # | Topic | Key Concepts |
|---|-------|-------------|
| 01 | [Why Reshaping Matters](#01-why-reshaping-matters) | shape compatibility, memory layout |
| 02 | [reshape()](#02-reshape) | change dimensions, -1 inference |
| 03 | [flatten() vs ravel()](#03-flatten-vs-ravel) | copy vs view, 1D output |
| 04 | [Adding & Removing Dimensions](#04-adding--removing-dimensions) | newaxis, expand_dims, squeeze |
| 05 | [Stacking Arrays](#05-stacking-arrays) | vstack, hstack, concatenate, stack |
| 06 | [Splitting Arrays](#06-splitting-arrays) | split, vsplit, hsplit |
| 07 | [Transpose & Swapaxes](#07-transpose--swapaxes) | T, transpose, swapaxes |
| 08 | [Engineering Applications](#08-engineering-applications) | images, signals, power systems |

---

## 01 · Why Reshaping Matters

### When Will You Use This?

| Task | Method |
|------|--------|
| Flatten image for neural network input | `image.reshape(-1)` |
| Convert 1D predictions to 2D grid | `predictions.reshape(10, 10)` |
| Add batch dimension | `data[np.newaxis, :]` |
| Stack multiple arrays | `np.vstack()`, `np.hstack()` |
| Combine sensor readings | `np.concatenate([a, b], axis=0)` |
| Transpose a matrix | `A.T` |
| Remove redundant dimensions | `np.squeeze(A)` |

> **Core rule:** Total number of elements must stay the same when reshaping.  
> `(2, 3)` → `(6,)` ✅ | `(2, 3)` → `(4, 3)` ❌

---

## 02 · reshape()

Change the shape of an array without changing its data.

```python
import numpy as np

A = np.array([1, 2, 3, 4, 5, 6])

A.reshape(2, 3)
# → [[1, 2, 3],
#    [4, 5, 6]]

A.reshape(3, 2)
# → [[1, 2],
#    [3, 4],
#    [5, 6]]
```

### Using -1 (auto-infer dimension)

```python
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

A.reshape(3, -1)   # → shape (3, 4)  — NumPy infers 4
A.reshape(-1, 4)   # → shape (3, 4)  — NumPy infers 3
A.reshape(-1)      # → shape (12,)   — full flatten
```

> 👉 `-1` tells NumPy: *"figure out this dimension based on total size."*  
> Only one `-1` is allowed per reshape call.

---

## 03 · flatten() vs ravel()

Both return a 1D version of the array — but behave differently in memory.

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A.flatten()   # → [1, 2, 3, 4, 5, 6]  — always a copy
A.ravel()     # → [1, 2, 3, 4, 5, 6]  — view when possible (faster)
```

| | `flatten()` | `ravel()` |
|---|---|---|
| Output | Always a copy | View when possible |
| Memory | Higher | Lower |
| Safe to modify | Yes | Modifying may affect original |
| Use when | You need an independent copy | Performance matters |

---

## 04 · Adding & Removing Dimensions

### Add a dimension — `np.newaxis`

```python
A = np.array([1, 2, 3])      # shape (3,)

A[np.newaxis, :]             # → shape (1, 3)  — row vector
A[:, np.newaxis]             # → shape (3, 1)  — column vector
```

### Add a dimension — `np.expand_dims()`

```python
A = np.array([1, 2, 3])

np.expand_dims(A, axis=0)    # → shape (1, 3)
np.expand_dims(A, axis=1)    # → shape (3, 1)
```

### Remove dimensions — `np.squeeze()`

```python
A = np.array([[[1, 2, 3]]])   # shape (1, 1, 3)

np.squeeze(A)                 # → shape (3,)
np.squeeze(A, axis=0)         # → shape (1, 3)
```

> 👉 `squeeze()` only removes dimensions of size 1. It will not collapse dimensions with size > 1.

---

## 05 · Stacking Arrays

Combine multiple arrays into one.

### Vertical stack — `np.vstack()`

```python
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

np.vstack([A, B])
# → [[1, 2, 3],
#    [4, 5, 6]]   — shape (2, 3)
```

### Horizontal stack — `np.hstack()`

```python
np.hstack([A, B])
# → [1, 2, 3, 4, 5, 6]   — shape (6,)
```

### Concatenate — `np.concatenate()`

```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

np.concatenate([A, B], axis=0)
# → [[1, 2],
#    [3, 4],
#    [5, 6],
#    [7, 8]]   — stacks along rows

np.concatenate([A, B], axis=1)
# → [[1, 2, 5, 6],
#    [3, 4, 7, 8]]   — stacks along columns
```

### Stack — `np.stack()`

Creates a new axis when stacking.

```python
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

np.stack([A, B], axis=0)   # → shape (2, 3)
np.stack([A, B], axis=1)   # → shape (3, 2)
```

| Function | New axis created | Requires same shape |
|----------|-----------------|---------------------|
| `vstack` | No | Yes (columns must match) |
| `hstack` | No | Yes (rows must match for 2D) |
| `concatenate` | No | Yes (all except concat axis) |
| `stack` | Yes | Yes (exact same shape) |

---

## 06 · Splitting Arrays

Divide one array into multiple parts.

```python
A = np.array([1, 2, 3, 4, 5, 6])

np.split(A, 3)
# → [array([1, 2]), array([3, 4]), array([5, 6])]

np.split(A, [2, 4])
# → [array([1, 2]), array([3, 4]), array([5, 6])]
```

### 2D splits

```python
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

np.hsplit(A, 2)   # split into 2 along columns
np.vsplit(A, 2)   # split into 2 along rows
```

---

## 07 · Transpose & Swapaxes

### Transpose — `.T`

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

A.T
# → [[1, 4],
#    [2, 5],
#    [3, 6]]   # shape (3, 2)
```

### np.transpose() — full axis control

```python
A = np.zeros((2, 3, 4))          # shape (2, 3, 4)

np.transpose(A, (1, 0, 2))       # → shape (3, 2, 4)
```

### np.swapaxes()

```python
A = np.zeros((2, 3, 4))
np.swapaxes(A, 0, 1)             # → shape (3, 2, 4)
```

---

## 08 · Engineering Applications

### Image processing — flatten for neural network

```python
image = np.random.randint(0, 255, (28, 28))   # grayscale image

flat = image.reshape(-1)           # → shape (784,) for NN input
batch = image[np.newaxis, :]       # → shape (1, 28, 28) for batch
```

### Signal processing — segment into windows

```python
signal = np.linspace(0, 1, 1000)

# Split into 10 windows of 100 samples each
windows = signal.reshape(10, 100)

# Stack multiple signals from sensors
s1 = np.sin(2 * np.pi * 50 * np.linspace(0, 1, 500))
s2 = np.cos(2 * np.pi * 50 * np.linspace(0, 1, 500))

sensor_matrix = np.vstack([s1, s2])   # shape (2, 500)
```

### Power systems — admittance matrix construction

```python
# Build Y-bus from branch data
branches = np.array([[0, 1, 0.1],
                     [1, 2, 0.2],
                     [0, 2, 0.15]])   # [from, to, impedance]

n_buses = 3
Y = np.zeros((n_buses, n_buses), dtype=complex)

# Reshape branch data for batch processing
from_bus = branches[:, 0].astype(int)
to_bus   = branches[:, 1].astype(int)
y        = 1 / branches[:, 2]         # admittance = 1 / impedance
```

---

## ⚡ Quick Reference

| Operation | Syntax | Result |
|-----------|--------|--------|
| Reshape | `A.reshape(r, c)` | New shape, same data |
| Auto-infer | `A.reshape(-1, c)` | NumPy calculates missing dim |
| Flatten (copy) | `A.flatten()` | 1D copy |
| Flatten (view) | `A.ravel()` | 1D view |
| Add row dim | `A[np.newaxis, :]` | shape `(1, n)` |
| Add col dim | `A[:, np.newaxis]` | shape `(n, 1)` |
| Remove size-1 dim | `np.squeeze(A)` | collapsed shape |
| Stack vertically | `np.vstack([A, B])` | rows combined |
| Stack horizontally | `np.hstack([A, B])` | cols combined |
| New axis stack | `np.stack([A, B])` | new dimension added |
| Concatenate | `np.concatenate([A, B], axis)` | flexible join |
| Split equally | `np.split(A, n)` | n equal parts |
| Transpose | `A.T` | axes flipped |
| Full transpose | `np.transpose(A, axes)` | custom axis order |

---

## 🛠️ Setup

```bash
pip install numpy
```

```python
import numpy as np
```

---

> 📌 Notes follow the structure: **Concept → Syntax → Code → Application**  
> Built by [@mohamadwael453](https://github.com/mohamadwael453)

# Lab